name: Parallel Performance Tests

on:
  push:
jobs:
  performance_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Cypress performance tests in parallel
        uses: cypress-io/github-action@v5
        with:
          record: true
          parallel: true
          command: npm run performance
