name: Parallel Acceptance Tests

on:
  push:
  schedule:
    - cron: '0 9 * * *'  # 9AM EST
jobs:
  acceptance_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cypress acceptance tests in parallel
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          command: npm run acceptance
