name: Parallel Performance Tests

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'  #every hour
jobs:
  performance_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress performance tests in parallel
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          command: npm run performance
